services:
  ai-studio-proxy:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      # 这是最后的、也是最关键的一步：为 Dockerfile 内部的指令明确指定正确的代理！
      args:
        PROXY_ADDR: http://host.docker.internal:7897
    container_name: ai-studio-proxy-container
    # ... 其余配置保持不变
    # ... 你的其他配置保持不变
    volumes:
      - ../auth_profiles:/app/auth_profiles
      - ../docker/.env:/app/.env:ro
      # - ../logs:/app/logs
      # - ../certs:/app/certs:ro
      # - ../browser_utils/custom_scripts:/app/browser_utils/custom_scripts:ro
      # - ../browser_utils/model_configs.json:/app/browser_utils/model_configs.json:ro
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${DEFAULT_FASTAPI_PORT:-2048}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
